"""Apply numbered SQL migrations.

Plain SQL rather than Alembic: the schema is still moving fast and a small team
gets more from reading one .sql file than from autogenerated revisions.

Each file runs exactly once, inside a transaction, and is recorded in
schema_migrations. Re-running the script is a no-op.

    uv run python migrations/apply.py          # apply pending
    uv run python migrations/apply.py --status # show what would run
"""

import argparse
import hashlib
import sys
from pathlib import Path

import psycopg

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.settings import get_settings  # noqa: E402

MIGRATIONS_DIR = Path(__file__).resolve().parent

BOOTSTRAP = """
CREATE TABLE IF NOT EXISTS schema_migrations (
    version     text PRIMARY KEY,
    checksum    text NOT NULL,
    applied_at  timestamptz NOT NULL DEFAULT now()
)
"""


def discover() -> list[Path]:
    return sorted(MIGRATIONS_DIR.glob("[0-9]*.sql"))


def checksum(sql: str) -> str:
    return hashlib.sha256(sql.encode("utf-8")).hexdigest()


def applied_versions(conn: psycopg.Connection) -> dict[str, str]:
    rows = conn.execute("SELECT version, checksum FROM schema_migrations").fetchall()
    return {version: digest for version, digest in rows}


def apply_all(conn: psycopg.Connection, dry_run: bool = False) -> int:
    conn.execute(BOOTSTRAP)
    conn.commit()

    already = applied_versions(conn)
    pending = 0

    for path in discover():
        version = path.stem
        sql = path.read_text(encoding="utf-8")
        digest = checksum(sql)

        if version in already:
            if already[version] != digest:
                # An applied migration was edited after the fact. Silently
                # skipping would leave environments quietly out of sync.
                raise SystemExit(
                    f"{version} was already applied but its contents changed. "
                    f"Add a new migration instead of editing this one."
                )
            print(f"  skip  {version}")
            continue

        pending += 1
        if dry_run:
            print(f"  pending {version}")
            continue

        print(f"  apply {version}")
        with conn.transaction():
            conn.execute(sql)
            conn.execute(
                "INSERT INTO schema_migrations (version, checksum) VALUES (%s, %s)",
                (version, digest),
            )

    return pending


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--status", action="store_true", help="list pending migrations without applying"
    )
    args = parser.parse_args()

    settings = get_settings()
    print(f"Migrations dir: {MIGRATIONS_DIR}")

    with psycopg.connect(settings.database_url, autocommit=False) as conn:
        pending = apply_all(conn, dry_run=args.status)

    if args.status:
        print(f"{pending} migration(s) pending")
    else:
        print(f"{pending} migration(s) applied")


if __name__ == "__main__":
    main()
